#!/bin/bash

for arg in "$@"; do
  length="$(wc -l < ./$arg)"
  k=0
  sum_x=0
  sum_y=0
  sum_xy=0
  sum_x2=0
  c=1
  # put input file into arrays and calculate sums
  while IFS= read -r line; do
    X[k]=$(echo $line | cut -d':' -f 1)
    Y[k]=$(echo $line | cut -d':' -f 2)
    X[k]=$(bc -l <<<"${X[k]}")
    Y[k]=$(bc -l <<<"${Y[k]}")
    XY[k]=$(bc -l <<<"${X[k]}*${Y[k]}")
    X2[k]=$(bc -l <<<"${X[k]}*${X[k]}")
    sum_x=$(bc -l <<<"${sum_x}+${X[k]}")
    sum_y=$(bc -l <<<"${sum_y}+${Y[k]}")
    sum_xy=$(bc -l <<<"${sum_xy}+${XY[k]}")
    sum_x2=$(bc -l <<<"${sum_x2}+${X2[k]}")
    k=$((k+1))
  done < "$arg"

  # calculate a
  temp1=$(bc -l <<<"$length*$sum_xy")
  temp2=$(bc -l <<<"$sum_x*$sum_y")
  dividend=$(bc -l <<<"($temp1)-($temp2)")
  temp1=$(bc -l <<<"$length*$sum_x2")
  temp2=$(bc -l <<<"$sum_x*$sum_x")
  divisor=$(bc -l <<<"($temp1)-($temp2)")

  zero=0

  if [ "$divisor" != $zero ]; then
    a=$(bc -l <<<"$dividend/$divisor")

    # calculate b
    temp2=$(bc -l <<<"$a*$sum_x")
    dividend=$(bc -l <<<"($sum_y)-($temp2)")
    b=$(bc -l <<<"$dividend/$length")

    # calculate err
    err=0
    for((i=0 ; i<$length ; i++)); do
      temp1=$(bc -l <<<"$a*${X[i]}")
      temp2=$(bc -l <<<"$temp1+$b")
      temp3=$(bc -l <<<"(${Y[i]})-($temp2)")
      temp3=$(bc -l <<<"$temp3*$temp3")
      err=$(bc -l <<<"$err+$temp3")
    done
    printf "\nFILE: %s, a=%.2f b=%.2f c=%.2f err=%.2f" $arg $a $b $c $err
  else
    printf "\nFILE: %s, a=-.-- b=-.-- c=-.-- err=-.-- (Division with zero)" $arg
  fi

done
printf "\n\n"
